version: "3.8"
services:
  web:
    container_name: example-web
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    volumes:
      - .:/code
  mongodb:
    image: mongo:latest
    container_name: example-mongodb
    ports:
      - 27017:27017
